version: "3"

networks:
  jekyll:
    external: false

services:
  garden:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jekyll
    restart: always
    networks:
      - jekyll
    volumes:
      - .:/usr/src/app/
    ports:
      - "4000:4000"

